Update CAPD Makefile
Signed-off-by: Chuck Ha <chuckh@vmware.com>

diff --git a/test/infrastructure/docker/Makefile b/test/infrastructure/docker/Makefile
--- a/test/infrastructure/docker/Makefile
+++ b/test/infrastructure/docker/Makefile
@@ -15,86 +15,229 @@
 # If you update this file, please follow:
 # https://suva.sh/posts/well-documented-makefiles/
 
+ROOT = ../../..
+
 .DEFAULT_GOAL:=help
 
 # Use GOPROXY environment variable if set
 GOPROXY := $(shell go env GOPROXY)
-GOPROXY ?= https://proxy.golang.org
-export GOPROXY
-
-REGISTRY ?= gcr.io/$(shell gcloud config get-value project)
-# Image URL to use all building/pushing image targets
-IMAGE_NAME ?= manager
-IMAGE_TAG ?= dev
-IMG ?= $(REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)
-
-# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
-CRD_OPTIONS ?= "crd:trivialVersions=true"
-
-TOOLS_DIR := hack/tools
-CONTROLLER_GEN_BIN := bin/controller-gen
-CONTROLLER_GEN := $(TOOLS_DIR)/$(CONTROLLER_GEN_BIN)
-RELEASE_NOTES_BIN := bin/release-notes
-RELEASE_NOTES := $(TOOLS_DIR)/$(RELEASE_NOTES_BIN)
-
-# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
-ifeq (,$(shell go env GOBIN))
-GOBIN=$(shell go env GOPATH)/bin
-else
-GOBIN=$(shell go env GOBIN)
+ifeq ($(GOPROXY),)
+GOPROXY := https://proxy.golang.org
 endif
+export GOPROXY
 
 # Active module mode, as we use go modules to manage dependencies
 export GO111MODULE=on
 
-all: manager
+# This option is for running docker manifest command
+export DOCKER_CLI_EXPERIMENTAL := enabled
+
+# Directories.
+TOOLS_DIR := hack/tools
+TOOLS_BIN_DIR := $(TOOLS_DIR)/bin
+BIN_DIR := bin
+
+# Binaries.
+CONTROLLER_GEN := $(TOOLS_BIN_DIR)/controller-gen
+CONVERSION_GEN := $(TOOLS_BIN_DIR)/conversion-gen
+
+# Define Docker related variables. Releases should modify and double check these vars.
+REGISTRY ?= gcr.io/$(shell gcloud config get-value project)
+STAGING_REGISTRY := gcr.io/k8s-staging-capi-docker
+PROD_REGISTRY := us.gcr.io/k8s-artifacts-prod/capi-docker
+IMAGE_NAME ?= capd-manager
+CONTROLLER_IMG ?= $(REGISTRY)/$(IMAGE_NAME)
+TAG ?= dev
+ARCH ?= amd64
+ALL_ARCH = amd64 arm arm64
+
+# Allow overriding the imagePullPolicy
+PULL_POLICY ?= Always
+
+all: test manager clusterctl
 
 help:  ## Display this help
 	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
 
-test: generate fmt vet manifests ## Run tests
-	go test ./api/... ./controllers/... -coverprofile cover.out
+## --------------------------------------
+## Testing
+## --------------------------------------
 
-manager: generate fmt vet ## Build manager binary
-	go build -o bin/manager main.go
+.PHONY: test
+test: generate lint ## Run tests
+	go test -v ./...
 
-run: generate fmt vet ## Run against the configured Kubernetes cluster in ~/.kube/config
-	go run main.go
+## --------------------------------------
+## Binaries
+## --------------------------------------
 
-install: manifests ## Install CRDs into a cluster
-	kubectl apply -f config/crd/bases
+.PHONY: manager
+manager: lint-full ## Build manager binary
+	go build -o $(BIN_DIR)/manager sigs.k8s.io/cluster-api/test/infrastructure/docker
 
-deploy: manifests ## Deploy controller in the configured Kubernetes cluster in ~/.kube/config
-	kubectl apply -f config/crd/bases
-	kustomize build config/default | kubectl apply -f -
+$(CONTROLLER_GEN): $(TOOLS_DIR)/go.mod # Build controller-gen from tools folder.
+	cd $(TOOLS_DIR); go build -tags=tools -o $(BIN_DIR)/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
 
-manifests: $(CONTROLLER_GEN) ## Generate manifests e.g. CRD, RBAC etc.
-	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
+$(CONVERSION_GEN): $(TOOLS_DIR)/go.mod
+	cd $(TOOLS_DIR); go build -tags=tools -o $(BIN_DIR)/conversion-gen k8s.io/code-generator/cmd/conversion-gen
 
-fmt: ## Run go fmt against code
-	go fmt ./...
+## --------------------------------------
+## Generate / Manifests
+## --------------------------------------
 
-vet: ## Run go vet against code
-	go vet ./...
-
+.PHONY: generate
 generate: $(CONTROLLER_GEN) ## Generate code
-	$(CONTROLLER_GEN) object:headerFile=./hack/boilerplate.go.txt paths=./api/...
+	$(MAKE) generate-manifests
+	$(MAKE) generate-go
 
-docker-build: test ## Build the docker image
-	docker build . -t ${IMG}
-	@echo "updating kustomize image patch file for manager resource"
-	sed -i'' -e 's@image: .*@image: '"${IMG}"'@' ./config/default/manager_image_patch.yaml
+.PHONY: generate-go
+generate-go: $(CONTROLLER_GEN) $(CONVERSION_GEN) ## Runs Go related generate targets
+	$(CONTROLLER_GEN) \
+		object:headerFile=$(ROOT)/hack/boilerplate/boilerplate.generatego.txt \
+		paths=./api/...
+	$(CONVERSION_GEN) \
+		--input-dirs=./api/v1alpha2 \
+		--output-file-base=zz_generated.conversion \
+		--go-header-file=$(ROOT)/hack/boilerplate/boilerplate.generatego.txt
 
+.PHONY: generate-manifests
+generate-manifests: $(CONTROLLER_GEN) ## Generate manifests e.g. CRD, RBAC etc.
+	$(CONTROLLER_GEN) \
+		paths=./api/... \
+		paths=./controllers/... \
+		crd:trivialVersions=true \
+		rbac:roleName=manager-role \
+		output:crd:dir=./config/crd/bases
+
+.PHONY: modules
+modules: ## Runs go mod to ensure modules are up to date.
+	go mod tidy
+	cd $(TOOLS_DIR); go mod tidy
+
+## --------------------------------------
+## Docker
+## --------------------------------------
+
+.PHONY: docker-build
+docker-build: ## Build the docker image for controller-manager
+	docker build --pull --build-arg ARCH=$(ARCH) ../../.. -t $(CONTROLLER_IMG)-$(ARCH):$(TAG)
+	MANIFEST_IMG=$(CONTROLLER_IMG)-$(ARCH) MANIFEST_TAG=$(TAG) $(MAKE) set-manifest-image
+	$(MAKE) set-manifest-pull-policy
+
+.PHONY: docker-push
 docker-push: ## Push the docker image
-	docker push ${IMG}
+	docker push $(CONTROLLER_IMG)-$(ARCH):$(TAG)
 
-# Build controller-gen
-$(CONTROLLER_GEN): $(TOOLS_DIR)/go.mod
-	cd $(TOOLS_DIR) && go build -o $(CONTROLLER_GEN_BIN) sigs.k8s.io/controller-tools/cmd/controller-gen
+## --------------------------------------
+## Docker — All ARCH
+## --------------------------------------
 
-$(RELEASE_NOTES) : $(TOOLS_DIR)/go.mod
-	cd $(TOOLS_DIR) && go build -o $(RELEASE_NOTES_BIN) -tags tools sigs.k8s.io/cluster-api/hack/tools/release
+.PHONY: docker-build-all ## Build all the architecture docker images
+docker-build-all: $(addprefix docker-build-,$(ALL_ARCH))
 
-.PHONY: release-notes
-release-notes: $(RELEASE_NOTES)
-	$(RELEASE_NOTES)
+docker-build-%:
+	$(MAKE) ARCH=$* docker-build
+
+.PHONY: docker-push-all ## Push all the architecture docker images
+docker-push-all: $(addprefix docker-push-,$(ALL_ARCH))
+	$(MAKE) docker-push-manifest
+
+docker-push-%:
+	$(MAKE) ARCH=$* docker-push
+
+.PHONY: docker-push-manifest
+docker-push-manifest: ## Push the fat manifest docker image.
+	## Minimum docker version 18.06.0 is required for creating and pushing manifest images.
+	docker manifest create --amend $(CONTROLLER_IMG):$(TAG) $(shell echo $(ALL_ARCH) | sed -e "s~[^ ]*~$(CONTROLLER_IMG)\-&:$(TAG)~g")
+	@for arch in $(ALL_ARCH); do docker manifest annotate --arch $${arch} ${CONTROLLER_IMG}:${TAG} ${CONTROLLER_IMG}-$${arch}:${TAG}; done
+	docker manifest push --purge $(CONTROLLER_IMG):$(TAG)
+	MANIFEST_IMG=$(CONTROLLER_IMG) MANIFEST_TAG=$(TAG) $(MAKE) set-manifest-image
+	$(MAKE) set-manifest-pull-policy
+
+.PHONY: set-manifest-image
+set-manifest-image:
+	$(info Updating kustomize image patch file for manager resource)
+	sed -i'' -e 's@image: .*@image: '"${MANIFEST_IMG}:$(MANIFEST_TAG)"'@' ./config/default/manager_image_patch.yaml
+
+.PHONY: set-manifest-pull-policy
+set-manifest-pull-policy:
+	$(info Updating kustomize pull policy file for manager resource)
+	sed -i'' -e 's@imagePullPolicy: .*@imagePullPolicy: '"$(PULL_POLICY)"'@' ./config/default/manager_pull_policy.yaml
+
+## --------------------------------------
+## Release
+## --------------------------------------
+
+GIT_TAG := $(shell git describe --match "test/infrastructure/docker/*" --abbrev=0 2>/dev/null)
+RELEASE_TAG := $(lastword $(subst /, ,$(GIT_TAG)))
+RELEASE_DIR := out
+
+$(RELEASE_DIR):
+	mkdir -p $(RELEASE_DIR)/
+
+.PHONY: release
+release: clean-release ## Builds and push container images using the latest git tag for the commit.
+	@if [ -z "${RELEASE_TAG}" ]; then echo "RELEASE_TAG is not set"; exit 1; fi
+	@if ! [ -z "$$(git status --porcelain)" ]; then echo "Your local git repository contains uncommitted changes, use git clean before proceeding."; exit 1; fi
+	git checkout "${GIT_TAG}"
+	# Push the release image to the staging bucket first.
+	REGISTRY=$(STAGING_REGISTRY) TAG=$(RELEASE_TAG) \
+		$(MAKE) docker-build-all docker-push-all
+	# Set the manifest image to the production bucket.
+	MANIFEST_IMG=$(PROD_REGISTRY)/$(IMAGE_NAME) MANIFEST_TAG=$(RELEASE_TAG) \
+		$(MAKE) set-manifest-image
+	PULL_POLICY=IfNotPresent $(MAKE) set-manifest-pull-policy
+	$(MAKE) release-manifests
+	$(MAKE) release-binaries
+
+.PHONY: release-manifests
+release-manifests: $(RELEASE_DIR) ## Builds the manifests to publish with a release
+	kustomize build config/default > $(RELEASE_DIR)/provider-components.yaml
+
+.PHONY: release-staging
+release-staging: ## Builds and push container images to the staging bucket.
+	REGISTRY=$(STAGING_REGISTRY) $(MAKE) docker-build-all docker-push-all release-alias-tag
+
+RELEASE_ALIAS_TAG=$(PULL_BASE_REF)
+
+.PHONY: release-alias-tag
+release-alias-tag: # Adds the tag to the last build tag.
+	gcloud container images add-tag $(CONTROLLER_IMG):$(TAG) $(CONTROLLER_IMG):$(RELEASE_ALIAS_TAG)
+
+## --------------------------------------
+## Cleanup / Verification
+## --------------------------------------
+
+.PHONY: clean
+clean: ## Remove all generated files
+	$(MAKE) clean-bin
+
+.PHONY: clean-bin
+clean-bin: ## Remove all generated binaries
+	rm -rf bin
+	rm -rf hack/tools/bin
+
+.PHONY: clean-release
+clean-release: ## Remove the release folder
+	rm -rf $(RELEASE_DIR)
+
+.PHONY: verify
+verify:
+	./hack/verify-boilerplate.sh
+	./hack/verify-doctoc.sh
+	./hack/verify-shellcheck.sh
+	$(MAKE) verify-modules
+	$(MAKE) verify-gen
+	$(MAKE) verify-modules
+
+.PHONY: verify-modules
+verify-modules: modules
+	@if !(git diff --quiet HEAD -- go.sum go.mod hack/tools/go.mod hack/tools/go.sum); then \
+		echo "go module files are out of date"; exit 1; \
+	fi
+
+.PHONY: verify-gen
+verify-gen: generate
+	@if !(git diff --quiet HEAD); then \
+		echo "generated files are out of date, run make generate"; exit 1; \
+	fi
